# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersProfile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sign', models.CharField(default=users.models.default_sign, max_length=50, verbose_name='个人签名')),
                ('info', models.CharField(max_length=150, verbose_name='个人描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isActived', models.BooleanField(default=True, verbose_name='激活')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
