# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usersprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='文章标题')),
                ('category', models.CharField(max_length=20, verbose_name='文章分类')),
                ('limit', models.CharField(max_length=10, verbose_name='文章权限')),
                ('introduce', models.CharField(max_length=90, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='文章创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='文章修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UsersProfile')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
